package com.example.lan_2;

public enum MessageType {
    JOIN,
    LOBBY_UPDATE,
    RETURN_TO_LOBBY,
    ERROR,
    READY,
    PAUSE,
    RESUME,
    EXIT,
    GAME_START,
    GAME_CANCEL,
    GAME_OVER,
    LEADERBOARD_UPDATE,
    PLAYER_MOVE,
    PLAYER_SHOOT,
    GAME_STATE_UPDATE,
    SCORE_UPDATE,
    PROJECTILE_UPDATE,
    TARGETS_SPAWN,
    TARGETS_UPDATE,
    TARGET_UPDATE,
    GET_LEADERBOARD,
    HIT
}
